apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: grafana
spec:
  replicas: 3
  selector:
    matchLabels:
       app: grafana
  strategy: {}
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana/grafana
        name: grafana
        #resources: {}
        resources:
          requests:
            cpu: "1m"
          limits:
            cpu: "2500m"  
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      #nodePort: 30000
status:
  loadBalancer: {}
---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: grafana
#   namespace: default
# spec:
#   scaleTargetRef:
#     kind: Deployment
#     name: grafana
#     apiVersion: apps/v1
#   minReplicas: 3
#   maxReplicas: 5
#   targetCPUUtilizationPercentage: 80

