apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: grafana
spec:
  replicas: 3
  selector:
    matchLabels:
       app: grafana
  strategy: {}
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana/grafana
        name: grafana
        #resources: {}
        resources:
          requests:
            cpu: "1m"
          limits:
            cpu: "2500m"  
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
status: {}