# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: grafana
#   namespace: default
# spec:
#   scaleTargetRef:
#     kind: Deployment
#     name: grafana
#     apiVersion: apps/v1
#   minReplicas: 3
#   maxReplicas: 5
#   targetCPUUtilizationPercentage: 80
